models/Section.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "section".
 *
 * @property int $id
 * @property string|null $title
 * @property int|null $status
 */
class Section extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'section';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status'], 'default', 'value' => null],
            [['status'], 'integer'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'status' => 'Status',
        ];
    }
}

controllers/SectionController.php
<?php

namespace app\controllers;

use app\models\SectionConductive;
use app\models\Users;
use Yii;
use app\models\Section;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ModulUsers;

/**
 * SectionController implements the CRUD actions for Section model.
 */
class SectionController extends Controller
{
    public function init()
    {
        parent::init();
        if (Yii::$app->user->isGuest) {
            $this->redirect('/index.php/site/login');
        }
        else {
            $user_id = Yii::$app->user->id;
            $checkUser = ModulUsers::find()->where(['user_id' => $user_id, 'modul_id' => 5])->one();
            if (!isset($checkUser)) {
                $this->redirect('/index.php/site/login');
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Section models.
     * @return mixed
     */
    public function actionIndex()
    {
        $models = Section::find()->all();

        return $this->render('index', [
            'models' => $models,
        ]);
    }

    public function actionView($id)
    {
        $section = Section::findOne($id);
        $users = Users::findAll(['status' => 1]);

        return $this->render('view', [
            'section' => $section,
            'users' => $users
        ]);
    }

    public function actionSaveConductive()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $user_id = Yii::$app->request->get('user');
            $section_id = Yii::$app->request->get('section');

            $model = new SectionConductive();
            $model->user_id = $user_id;
            $model->section_id = $section_id;
            $model->save();

            return ['status' => 'success'];
        }
    }


    /**
     * Creates a new Section model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $model = new Section();

            if (isset($_GET['title']) && !empty($_GET['title'])) {
                $model->title = Yii::$app->request->get('title');
                $model->status = 1;
                $model->save();
                return ['status' => 'success'];
            }

            return [
                'status' => 'success',
                'content' => $this->renderAjax('_form', [
                    'model' => $model,
                ])
            ];
        }
    }

    /**
     * Updates an existing Section model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $model = $this->findModel($id);

            if (isset($_GET['title']) && !empty($_GET['title'])) {
                $model->title = $_GET['title'];
                $model->save();
                return ['status' => 'success'];
            }

            return [
                'status' => 'success',
                'content' => $this->renderAjax('update', [
                    'model' => $model,
                ])
            ];
        }
    }

    /**
     * Deletes an existing Section model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionArchive($id)
    {
        $model = Section::findOne($id);
        $model->status = 0;
        $model->save();

        return $this->redirect(['index']);
    }
    public function actionActive($id)
    {
        $model = Section::findOne($id);
        $model->status = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Section model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Section the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Section::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/section/_form.php
<div class="row">
    <label class="col-lg-12 col-md-3 form-control-label">Bo'lim nomi</label>
    <div class="col-lg-12 col-md-9 form-group">
        <input type="text" class="form-control" id="section-title">
        <small class="section_error hidden text-danger" style="font-size: 12px">Maydon bo'sh bo'lishi mumkin emas!</small>
    </div>
</div>
<style>
    .hidden {
        display: none;
    }
</style>

views/section/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = "Bo'limlar";
?>
    <style>
        .section-index {
            background-color: white;
            padding: 30px;
            -webkit-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
            -moz-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
            box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        }
    </style>
    <div class="section-index">
        <div class="row">
            <div class="col-md-6">
                <h1 class="m-0"><?= Html::encode($this->title) ?></h1>
            </div>
            <div class="col-md-6">
                <?= Html::a("Bo'lim qo'shish", [''], ['class' => 'btn btn-success add float-right m-0', 'style' => 'margin-top: 30px;', 'data-target' => "#examplePositionCenter", 'data-toggle' => "modal"]) ?>
            </div>
        </div>

        <div class="row mt-10">
            <div class="col-md-12">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Bo'lim nomi</th>
                        <th>Holati</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (isset($models) and !empty($models)): ?>
                        <?php foreach ($models as $model): ?>
                            <tr>
                                <td><?= $model->title ?></td>
                                <td>
                                    <?php if ($model->status == 1): ?>
                                        <span class="badge badge-success">Faol</span>
                                    <?php else: ?>
                                        <span class="badge badge-danger">Faol emas</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <a style="margin-right:10px;color: #3c8dbc;cursor:pointer;" class='update_section'
                                       data-update="<?= $model->id ?>" data-target="#examplePositionCenter"
                                       data-toggle="modal">
                                        <svg aria-hidden="true"
                                             style="display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em;width:1em"
                                             xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                            <path fill="currentColor"
                                                  d="M498 142l-46 46c-5 5-13 5-17 0L324 77c-5-5-5-12 0-17l46-46c19-19 49-19 68 0l60 60c19 19 19 49 0 68zm-214-42L22 362 0 484c-3 16 12 30 28 28l122-22 262-262c5-5 5-13 0-17L301 100c-4-5-12-5-17 0zM124 340c-5-6-5-14 0-20l154-154c6-5 14-5 20 0s5 14 0 20L144 340c-6 5-14 5-20 0zm-36 84h48v36l-64 12-32-31 12-65h36v48z"></path>
                                        </svg>
                                    </a>
                                    <?php if ($model->status == 1): ?>
                                        <a style="margin-right:10px;"
                                           href="<?= Url::to(['section/archive', 'id' => $model->id]) ?>"><i
                                                    style="font-size: 1.2em;" class="fa fa-times"
                                                    aria-hidden="true"></i></a>
                                    <?php else: ?>
                                        <a style="margin-right:10px;"
                                           href="<?= Url::to(['section/archive', 'id' => $model->id]) ?>"><i
                                                    style="font-size: 1.2em;" class="fa fa-check"
                                                    aria-hidden="true"></i></a>
                                    <?php endif; ?>
                                    <a style="margin-right:10px;"
                                       href="<?= Url::to(['section/view', 'id' => $model->id]) ?>"><i
                                                style="font-size: 1.2em;" class="fa fa-eye" aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php
$js = <<<JS

    $(document).on("click", '.add', function() {
        $(".modal-footer .btn-primary").removeClass().addClass("btn btn-primary save"); 
        $('.modal-header').text("Bo'lim qo'shish")
        $.ajax({ 
            url: '/section/create',
            type: 'get',
            dataType: 'json',
            success: function(response) {
                if (response.status == "success") {
                    $('.modal-body').html(response.content)
                }
            }
        })
    });

    $(document).on("click", '.update_section', function() {
        var update_id = $(this).attr('data-update')
        $(".modal-footer .btn-primary").removeClass().addClass("btn btn-primary update_save").attr('data-update',update_id);
        $('.modal-header').text("Bo'lim o'zgartirish")
        $.ajax({ 
            url: '/section/update?id='+update_id,
            type: 'get',
            dataType: 'json',
            success: function(response) {
                if (response.status == "success") {
                    $('.modal-body').html(response.content)
                }
            }
        })
    });

    $(document).on("click", '.save', function() {
        var title = $('#section-title').val()
        if (title.trim() != '') {
            var _this = $(this)
            $(this).attr('disabled',true)
            $(this).attr('readonly',true)
            $.ajax({
                type: 'get',
                url: '/section/create',
                data: {
                    title: title
                },  
                dataType: 'json',
                success: function(response) {
                    _this.attr('disabled',true)
                    _this.attr('readonly',true)

                    if (response.status == "success") {
                        location.reload();
                    }
                }
            })
        } else {
            $('#section-title').addClass('is-invalid')
            $('.section_error').removeClass('hidden')  
        }
    });

    $(document).on("click", '.update_save', function() {
        var title = $('#section-title').val()
        var update_id = $(this).attr('data-update')
        if (title.trim() != '') {
            var _this = $(this)
            $(this).attr('disabled',true)
            $(this).attr('readonly',true)

            $.ajax({
                type: 'get',
                url: '/section/update?id='+update_id,
                data: {
                    title: title
                },  
                dataType: 'json',
                success: function(response) {
                    _this.attr('disabled',true)
                    _this.attr('readonly',true)
                    if (response.status == "success") {
                        location.reload();
                    }
                }
            })
        }else{
            $('#section-title').addClass('is-invalid')
            $('.section_error').removeClass('hidden')  
        }
    });

JS;
$this->registerJs($js);
?>

views/section/update.php
<div class="row">
    <label class="col-lg-12 col-md-3 form-control-label">Bo'lim nomi</label>
    <div class="col-lg-12 col-md-9 form-group">
        <input type="text" class="form-control" value='<?=$model->title?>' id="section-title">
        <small class="section_error hidden text-danger" style="font-size: 12px">Maydon bo'sh bo'lishi mumkin emas!</small>
    </div>
</div>
<style>
    .hidden {
        display: none;
    }
</style>

views/section/view.php
<div class="row index-conductive">
    <div class="col-md-12 mb-20">
        <h2 class="m-0">Shochik qo'shish</h2>
    </div>
    <div class="col-md-6">
        <input type="text" id="section" data-id="<?= $section->id ?>" value="<?= $section->title ?>" readonly class="form-control" name="">
    </div>
    <div class="col-md-6">
        <select id="conductive" class="form-control">
            <?php
                if (isset($users) and !empty($users)){
                    foreach ($users as $key => $value){ ?>
                        <option value="<?php echo $value->id ?>">
                            <?php echo $value->username; ?>
                        </option>
                    <?php }
                }
            ?>
        </select>
    </div>
    <div class="col-md-12">
        <div class="btn btn-success float-right mt-20 save_conductive">Saqlash</div>
    </div>
</div>

<style>
    .index-conductive {
        background-color: white;
        padding: 30px;
        -webkit-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        -moz-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
    }
</style>

<?php
$js = <<<JS
    $(document).on('click', '.save_conductive', function(){
        var user = $("#conductive").val()
        var section = $("#section").val()
        $.ajax({
            url: 'save-conductive',
            data: {
                user: user,
                section: section
            },
            dataType: 'json',
            type: 'get',
            success: function(response) {
                if (response.status == 'success') {
                    location.reload()  
                }
            }
        })
    })
JS;
$this->registerJs($js);
?>