models/Orders.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $created_date
 * @property string|null $exit_date
 * @property int|null $status
 * @property int|null $order_type
 * @property int|null $code
 * @property int|null $client_id
 * @property int|null $price
 * @property int|null $category_id
 * @property string|null $order_name
 * @property int|null $order_from
 * @property int|null $proirity
 * @property string|null $deadline_price
 * @property int|null $approved
 * @property int|null $specification_status
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_date', 'exit_date', 'deadline_price'], 'safe'],
            [['status', 'specification_status', 'order_type', 'client_id', 'price', 'category_id', 'order_from', 'proirity', 'approved'], 'default', 'value' => null],
            [['status', 'specification_status', 'client_id', 'price', 'category_id', 'order_from', 'proirity', 'approved', 'code'], 'integer'],
            [['order_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_date' => 'Created Date',
            'exit_date' => 'Exit Date',
            'status' => 'Status',
            'client_id' => 'Client ID',
            'price' => 'Price',
            'category_id' => 'Category ID',
            'order_name' => 'Order Name',
            'order_from' => 'Order From',
            'proirity' => 'Proirity',
            'deadline_price' => 'Deadline Price',
            'approved' => 'Approved',
            'code' => 'Code',
        ];
    }

    public function getClients()
    {
        return $this->hasOne(Clients::class, ['id' => 'client_id']);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use app\models\Modules;
use app\models\Notification;
use Yii;
use app\models\Orders;
use app\models\Clients;
use app\models\Docs;
use app\models\Category;
use app\models\CategoryDocs;
use app\models\OrdersDocs;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ModulUsers;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * {@inheritdoc}
     */

    public function init()
    {
        parent::init();
        if (Yii::$app->user->isGuest) {
            $this->redirect('/index.php/site/login');
        }
        else {
            $user_id = Yii::$app->user->id;
            $checkUser = ModulUsers::find()->where(['user_id' => $user_id, 'modul_id' => 3])->one();
            if (!isset($checkUser)) {
                $this->redirect('/index.php/site/login');
            }
        }
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $sql = "
            SELECT 
               c.title as category,
               o.created_date as enter_date,
               ct.phone_number as phone_number,
               ct.phone_number_2 as phone_number_2,
               ct.company_name as company_name,
               o.proirity as priority,
               o.approved as approved,
               o.order_name as order_name,
               o.status as status,
               o.id as order_id,
               o.price as price,
               o.deadline_price as deadline_price,
               o.order_from as order_from,
               m.title AS module_name,
               n.module_id AS module_id
           FROM orders as o
           INNER JOIN notification AS n ON o.id = n.order_id
           INNER JOIN modules AS m ON n.module_id = m.id
           lEFT JOIN category AS c ON c.id = o.category_id AND c.status = :status
           INNER JOIN clients AS ct ON o.client_id = ct.id 
           WHERE n.end_date IS NULL
           GROUP BY 
               o.id,
               c.title,
                o.created_date,
                ct.phone_number,
                ct.phone_number_2,
                ct.company_name,
                o.proirity,
                o.approved,
                o.order_name,
                o.status,
                o.price,
                o.deadline_price,
                o.order_from,
                m.title,
                n.module_id 
        ";

        $model = Yii::$app->db->createCommand($sql)
        ->bindValue(':status', 1)
        ->queryAll();

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    public function actionCategory()
    {
        $sql = "
            SELECT 
                c.id AS category_id,
                d.id AS docs_id,
                c.title AS category,
                d.title AS docs
            FROM category_docs AS cd
            LEFT JOIN category AS c ON c.id = cd.category_id AND c.status = :status
            LEFT JOIN docs AS d ON d.id = cd.docs_id AND d.status = :status
            ORDER BY cd.id ASC
        ";

        $model = Yii::$app->db->createCommand($sql)
        ->bindValue(':status', 1)
        ->queryAll();

        $arr = [];
        if (isset($model) && !empty($model)) {
            $n = 0;
            foreach ($model as $key => $value) {
                $arr[$value['category_id']]['category_id'] = $value['category_id'];
                $arr[$value['category_id']]['category'] = $value['category'];
                $arr[$value['category_id']]['list'][$n]['id'] = $value['docs_id'];
                $arr[$value['category_id']]['list'][$n]['title'] = $value['docs'];
                $n++;
            }
        }

        return $this->render('category', [
            'arr' => $arr,
        ]);
    }

    public function actionSave()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if(isset($_GET['cat']) && !empty($_GET['cat'])){
                $cat = intval($_GET['cat']);
                if(isset($_GET['docs']) && !empty($_GET['docs'])){
                    $docs_ex = explode(',', $_GET['docs']);
                    $arr = [];
                    $arr2 = [];
                    $get_docs = Docs::find()->where('status = :status', [':status' => 1])->All(); 
                    foreach ($docs_ex as $key => $value) {
                        if(is_numeric($value) == true){
                            foreach ($get_docs as $key => $value2) {
                                $docs_id = $value2->id;
                                if($value == $docs_id){
                                    $arr[] = $value;
                                }
                            }
                        }
                        elseif(is_string($value) == true){
                            $arr2[] = $value;
                        }
                    }
                if(isset($_GET['phone_number']) && !empty($_GET['phone_number'])){
                    $phone_number = intval($_GET['phone_number']);
                    if(isset($_GET['phone_number_2']) && !empty($_GET['phone_number_2'])){
                        $phone_number_2 = intval($_GET['phone_number_2']);
                        if(isset($_GET['project_name']) && !empty($_GET['project_name'])){
                            $project_name = htmlspecialchars($_GET['project_name']);
                                if(isset($_GET['company_name']) && !empty($_GET['company_name'])){
                                    $company_name = htmlspecialchars($_GET['company_name']);
                                    if(isset($_GET['from'])){
                                        $from = htmlspecialchars($_GET['from']);
                                        if(isset($_GET['price_date']) && !empty($_GET['price_date'])){
                                            $price_date = $_GET['price_date'];
                                            if(isset($_GET['price_time']) && !empty($_GET['price_time'])){
                                                $price_time = $_GET['price_time'];
                                                if(isset($_GET['proirity'])){
                                                    $proirity = intval($_GET['proirity']);
                                                    if(isset($_GET['price']) && !empty($_GET['price'])){
                                                        $price = intval($_GET['price']);
                                                        if(isset($_GET['client_email']) && !empty($_GET['client_email'])){
                                                            $client_email = htmlspecialchars($_GET['client_email']);
                                                            if(isset($_GET['client_name']) && !empty($_GET['client_name'])){
                                                                $client_name = htmlspecialchars($_GET['client_name']);
                                                                if(isset($_GET['country']) && !empty(['country'])){
                                                                    $country =  htmlspecialchars($_GET['country']);
                                                                    $db = Yii::$app->db;
                                                                    $transaction = $db->beginTransaction();
                                                                    try {
                                                                        $clients = new Clients;
                                                                        $clients->phone_number = $phone_number;
                                                                        $clients->phone_number_2 = $phone_number_2;
                                                                        $clients->company_name = $company_name;
                                                                        $clients->face_name = $client_name;
                                                                        $clients->country = $country;
                                                                        $clients->email = $client_email;
                                                                        $clients->save(false);
                                                                        
                                                                        $orders = new Orders;
                                                                        $orders->created_date = date('Y-m-d H:i:s');
                                                                        $orders->deadline_price = date('Y-m-d H:i:s', strtotime(date($price_date." ".$price_time.":00")));
                                                                        $orders->price = $price;
                                                                        $orders->order_name = $project_name;
                                                                        $orders->order_from = $from;
                                                                        $orders->proirity = $proirity;
                                                                        $orders->approved = 0;
                                                                        $orders->category_id = $cat;
                                                                        $orders->status = 0;
                                                                        $orders->client_id = $clients->id;

views/orders/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Category;
use app\models\CategoryDocs;
// use app\models\OrdersDocs;
use app\models\Docs;


/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<h1>Buyurtma qo'shish</h1>
<br>
<!-- <form id="order_forma" action="#"> -->
    <div class="row">
        <div class="col-md-6">
            <div class="select2-primary">
                <label for="mySelect2" style="font-size: 15px">Kategoriyani tanlang</label>
                <select class="form-control cat mySelect2" data-plugin="select2">
                    <?php
                    // $getCategory = Category::find()->all();
                    if(isset($getCategory) && !empty($getCategory)){
                        foreach ($getCategory as $key => $value){
                            ?>
                            <option value="<?php echo $value->id; ?>">
                                <?php echo $value->title; ?>
                            </option>
                        <?php 
                        }
                    }else {
                        ?>
                        <option disabled selected>Kategoriya mavjud emas</option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            
        </div>
            <div class="col-md-6 div_pr ">
                    <div class="select2-primary order_docs_div">
                        <label for="mySelect2"  style="font-size: 15px">Hujjat tanlang</label>
                        <small class="error_branch hidden text-danger">( Maydon bo`sh bo'lishi mumkin emas! )</small>
                        <select class="form-control order_docs mySelect2" id="select3" multiple="multiple" data-plugin="select2">
                            <?php
                            if(isset($documents) && !empty($documents)){
                                foreach ($documents as $key => $value){
                                    ?>
                                    <option  class="documents" value="<?php echo $value['id']; ?>">
                                        <?php echo $value['docs']; ?>
                                    </option>
                                <?php
                                } 
                            } else {
                                ?>
                                <option disabled selected>Dokument mavjud emas</option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>

    <br>
    <div class="row">
        <div class="col-md-6 div_phone_number">
            <label>Telefon raqam</label>
            <input type="text"  class="phone_number form-control">
        </div>
        <div class="col-md-6 div_phone_number_2">
            <label>Telefon raqam 2</label>
            <input type="text" class="form-control phone_number_2">    
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6 div_client_name">
            <label>Mijoz ismi</label>
            <input type="text"  class="client_name form-control">
        </div>
        <div class="col-md-6 div_email">
            <label>Mijoz emaili</label>
            <input type="text" class="form-control  client_email">    
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6 div_company_name">
            <label>Kompaniya nomi</label>
            <input type="text"  class="company_name form-control">
        </div>
        <div class="col-md-6 div_country">
            <label>Mijoz manzili</label>
            <input type="text" class="form-control country">    
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6 div_price">
            <label>Buyurtma narxi</label>
            <input type="number" class="price form-control">
            
        </div>
        <div class="col-md-6 div_pr_name">
            <label>Loyiha nomi</label>
            <input type="text" class="project_name form-control col-xl-12 col-md-6">            
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-md-4">
            <label>Narx taqdim etish sanasi</label>
            <div class="example-wrap">
              <div class="example datepair-wrap" data-plugin="datepair">
                <div class="input-daterange-wrap">
                  <div class="input-daterange">
                    <div class="input-group div_date">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="icon wb-calendar" aria-hidden="true"></i>
                        </span>
                      </div>
                      <input type="text" data-date-format='dd.mm.yyyy'  id="datepicker" class="datepicker price_date form-control datepair-date datepair-start" data-plugin="datepicker">
                    </div>
                    <div class="input-group div_time">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="icon wb-time" aria-hidden="true"></i>
                        </span>
                      </div>
                        <input type="text" class="timepicker price_time form-control" data-plugin="clockpicker" data-autoclose="true">       
                    </div>
                  </div>
                </div>
              </div>
            </div>        
        </div>
        <div class="col-md-4">
            <label>Buyurtma darajasini tanlang</label>
            <div style="margin-left: -20px;" class=" col-xl-12">
              <div class="example">
                <select class="proirity form-control" data-plugin="select2">
                  <optgroup label="Buyurtma darajasini tanlang">
                    <option value="0">Tezkor</option>
                    <option value="1">Oddiy</option>
                    <option value="2">Kechiktirilgan</option>
                  </optgroup>
                </select>
              </div>
            </div>
            
        </div>
        <div class="col-md-4">
            <label>Buyurtma qayerdan qabul qilinyapti</label>
            <div style="margin-left: -20px;" class=" col-xl-12">
              <div class="example">
                <select class="form-control from" data-plugin="select2">
                  <optgroup label="Buyurtma qayerdan">
                    <option value="0">IN</option>
                    <option value="1">OUT</option>
                  </optgroup>
                </select>
              </div>
            </div>
        </div>
    </div>
<!-- </form> -->
<br>

<button class="btn btn-success save float-right">Saqlash</button>
<br>
<br>

<style type="text/css">
    .docs_fail{
        border: solid red 1px;
    }
    .hidden{
        display: none;
    }
</style>

<?php
$js = <<<JS
$(function(){

    $("#select3").select2({
        tags: true
    });

    $( ".datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });

});



$(document).on('change', '.mySelect2', function() {
      var sel = $(this).val()
       $('.save').attr('data-cat', sel)

})


$(document).on("click", '.save', function() {
    var docs = $(this).attr('data-cat')
    var cat = $('.cat').val();
    var project_name = $('.project_name').val();
    var phone_number = $('.phone_number').val();
    var phone_number_2 = $('.phone_number_2').val();
    var company_name = $('.company_name').val();
    var client_name = $('.client_name').val();
    var client_email = $('.client_email').val();
    var price = $('.price').val();
    var country = $('.country').val();
    var price_date = $('.price_date').val();
    var price_time = $('.price_time').val();
    var from = $('.from').val();
    var proirity = $('.proirity').val();
    $.ajax({
        data: {
            docs: docs,
            cat: cat,
            project_name: project_name,
            price: price,
            phone_number: phone_number,
            phone_number_2: phone_number_2,
            client_name: client_name,
            client_email: client_email,
            country: country,
            company_name: company_name,
            price_date: price_date,
            price_time: price_time,
            from: from,
            proirity: proirity
        },  
        url: '/orders/save',
        type: 'get',
        dataType: 'json',
        success: function(response) {
            if (response.status == "success") {
                window.location.href = '/orders/index';
            }
            else if(response.status == "project_name_fail") 
            {
                $('.project_name').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Loyiha nomini kiritmadingiz!</div>`);
                $('.div_pr_name').append(input);
            }
            else if(response.status == "phone_number_fail") 
            {
                $('.phone_number').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Telefon raqam kiritmadingiz!</div>`);
                $('.div_phone_number').append(input);
            }
            else if(response.status == "phone_number_2_fail") 
            {
                $('.phone_number_2').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Telefon raqam kiritmadingiz!</div>`);
                $('.div_phone_number_2').append(input);
            }
            else if(response.status == "client_name_fail") 
            {
                $('.client_name').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Ism maydonini toldirmadingiz!</div>`);
                $('.div_client_name').append(input);
            }
            else if(response.status == "client_email_fail") 
            {
                $('.client_email').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Email pochta kiritmadingiz!</div>`);
                $('.div_email').append(input);
            }
            else if(response.status == "price_date_fail") 
            {
                $('.price_date').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Narx taqdim etadigan sana kiritmadingiz!</div>`);
                $('.div_date').append(input);
            }
            else if(response.status == "country_fail") 
            {
                $('.country').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Manzil kiritmadingiz!</div>`);
                $('.div_country').append(input);
            }
            else if(response.status == "price_time_fail") 
            {
                $('.price_time').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback">Narx taqdim etadigan sana kiritmadingiz!</div>`);
                $('.div_time').append(input);
            }
            // else if(response.status == "docs_fail") 
            // {
            //     $('.order_docs').addClass('docs_fail');
            //     var input = $(`<div class="invalid-feedback">Hujjat tanlamadingiz!</div>`);
            //     $('.order_docs_div').append(input);
            // }
            else if(response.status == "company_name_fail") 
            {
                $('.company_name').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback"> Kompaniya nomi maydonini toldiring!</div>`);
                $('.div_company_name').append(input);
            }
            else if(response.status == "price_fail") 
            {
                $('.price').addClass('is-invalid');
                var input = $(`<div class="invalid-feedback"> Narx nomi maydonini toldiring!</div>`);
                $('.div_price').append(input);
            }
            else if(response.status == 'docs_fail'){
                $('.order_docs').parent().addClass('has-error')
                $('.error_branch').removeClass('hidden')
            }
        }
    })
});


$(document).on('change', '.cat', function() {
  var cat = $('.cat').val();
  $.ajax({
        url: '/orders/cat_filter',
        data: {
            cat:  cat
        },
        type: 'get',
        dataType: 'json',
        success:function(response){
            if(response.status == "success"){
                $('#select3').html(response.content)
            }
        }
    })
});




JS;
$this->registerJs($js);
?> 

views/orders/category.php
<?php

use yii\helpers\Html;


$this->title = 'Kategoriyalar';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-index">

    <div class="row">
        <div class="text-left col-md-6">
            <h1 class="m-0"><?= Html::encode($this->title) ?></h1>
        </div>

        <div class="text-right col-md-6">
            <button  class="btn btn-success float-right add" id="add_cat" data-target="#examplePositionCenter" data-toggle="modal">Kategoriya qo'shish</button>
        </div>

                <div class="modal fade" id="examplePositionCenter" aria-hidden="true" aria-labelledby="examplePositionCenter"
                     role="dialog" tabindex="-1">
                    <div class="modal-dialog modal-simple modal-center">
                        <div class="modal-content">
                            <div class="modal-header" style="font-size: 25px">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                                <h4 class="modal-title"> Kategoryaga hujjat qo'shish</h4>
                            </div>
                            <div class="modal-body">
                                <p>Malumot yo'q!</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Yopish</button>
                                <button type="button" class="btn btn-primary">Saqlash</button>
                            </div>
                        </div>
                    </div>
                </div>

    </div>
    <hr>


    <div class="panel">
      <div class="panel-body">
        <table class="table table-bordered toggle-circle" id="exampleFootableFiltering" style="text-align: center;">
          <thead>
            <tr>
              <th>#</th>
              <th>Kategoriya nomi</th>
              <th>Hujjatlar</th>
            </tr>
          </thead>
          <tbody>
            <?php 
                if(isset($arr) && !empty($arr)){
                    $i = 1;
                    foreach ($arr as $key => $value) {
                        ?>
                            <tr style="height: 60px;">
                                <td><?= $i++ ?></td>
                                <td><?= $value['category'] ?></td>
                                <td style="padding-top: 20px;">
                                	<?php 
	                                    if(isset($value['list']) && !empty($value['list'])){
	                                      foreach ($value['list'] as $key => $list) {
	                                        if(isset($list['title']) && !empty($list['title'])){
	                                          echo "<span class='bg-blue-grey-100' style='padding: 10px; border-radius: 5px;   margin-left: 10px; '>".$list['title']." &nbsp <i class='wb-close del' cat_id='".$value['category_id']."' docs_id='".$list['id']."'  style='cursor: pointer;'></i></span>";
	                                        }
	                                        else{
	                                          echo "<span class='bg-blue-grey-100' style='padding: 10px; border-radius: 5px; margin-left: 10px; '> Hujjat mavjud emas </span>";                                        
	                                        }
	                                      }
	                                    }
                                	 ?>
                                </td>
                            </tr>
                        <?php
                    }
                }
             ?>
          </tbody>
        </table>
      </div>
    </div>
</div>




<?php
$js = <<<JS

$(document).on("click", '.del', function() {
    if(confirm('Ushbu hujjatni o`chirishni tasdiqlaysizmi') == true){
      var cat_id = $(this).attr('cat_id');
      var docs_id = $(this).attr('docs_id'); 
    }
$.ajax({
  data: {
     cat_id: cat_id,
     docs_id: docs_id
  }, 
  url: '/orders/del',
  type: 'get',
  dataType: 'json',
     success: function(response) {
         if (response.status == "success") {
             location.reload();
         }
         else{
          alert('Xatolik')
         }
       }
    })
});


$(document).on("click", '.add', function() {
    $(".modal-footer .btn-primary").removeClass().addClass("btn btn-primary save"); 
    $.ajax({ 
        url: '/orders/category_add',
        type: 'get',
        dataType: 'json',
             success: function(response) {
                 if (response.status == "success") {
                     $('.modal-body').html(response.content)
                     $('.modal-header').text('Kategoriya qo`shish')
                 }
             }
    })
});

$(document).on('change', '.mySelect2', function() {
      var sel = $(this).val()
       $('.save').attr('data-cat', sel)
})

$(document).on('change', '.mySelect3', function() {
      var sel = $(this).val()
       $('.save').attr('data-doc', sel)
})


$(document).on("click", '.save', function() {
    // var cat = $(this).attr('data-cat')
    var cat = $('#cat').val()
    var doc = $(this).attr('data-doc')
    $.ajax({
        data: {
            cat: cat,
            doc: doc,
        },  
        url: '/orders/category_save',
        type: 'get',
        dataType: 'json',
            success: function(response) {
                if (response.status == "success") {
                    location.reload();
                }
                else{
                    $("#examplePositionTop").modal('toggle');
                    alert('Xatolik');
                }
            }
    })
});

JS;
$this->registerJs($js);
?>  

views/orders/category_form.php
<?php 

use app\models\Category;
use app\models\Docs;

 ?>        

<div>
    <label>Kategoriya nomini kiriting</label>
    <input type="text" id="cat" class="form-control" name="">
</div>
<br>

<div class=" div_pr docs">
    <div class="select2-primary">
        <label for="mySelect2" style="font-size: 15px">Hujjat tanlang</label>
        <select class="form-control docs_select mySelect3" id="select3" multiple="multiple" data-plugin="select2">
            <?php
            $getCategory =  Docs::find()->all();
                foreach ($getCategory as $key => $value): ?>
                    <option class="col-md-12" value="<?php echo $value->id; ?>">
                        <?php echo $value->title; ?>
                    </option>
                <?php endforeach 
                ?>
        </select>
    </div>
</div>



<script>
    $("#select2").select2({
        tags: true
    });
    $("#select3").select2({
        tags: true
    });


</script>

views/orders/select_form.php
<?php foreach ($docs as $key => $value): ?>
    <option value="<?php echo $value['id']; ?>">
        <?php echo $value['docs']; ?>
    </option>
<?php endforeach ?>