models/Supplier.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "supplier".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $status
 */
class Supplier extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'supplier';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'user_id'], 'integer', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Ismi',
            'status' => 'Holati',
        ];
    }

    public function getName()
    {
        return $this->hasOne(Users::class, ['id' => 'user_id']);
    }
}

controllers/SupplierController.php
<?php

namespace app\controllers;

use app\models\Nakladnoy;
use app\models\NakladnoyDetails;
use Yii;
use app\models\Supplier;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ModulUsers;

/**
 * SupplierController implements the CRUD actions for Supplier model.
 */
class SupplierController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();
        if (Yii::$app->user->isGuest) {
            $this->redirect('/index.php/site/login');
        }
        else {
            $user_id = Yii::$app->user->id;
            $checkUser = ModulUsers::find()->where(['user_id' => $user_id, 'modul_id' => 8])->one();
            if (!isset($checkUser)) {
                $this->redirect('/index.php/site/login');
            }
        }
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Supplier models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Supplier::find()->orderBy(['id' => SORT_ASC]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSupplierOrders()
    {
        $query = Supplier::find()
            ->select('n.id, n.code, n.enter_date, n.created_date, n.status, n.end_date')
            ->innerJoin(
                'nakladnoy as n', 'supplier.id = n.supplier_id'
            )
            ->where(['supplier.user_id' => Yii::$app->user->id])
            ->asArray()
            ->orderBy(['n.status' => SORT_ASC]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('nakladnoys', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStart()
    {
        $id = Yii::$app->request->get('id');
        $updateNak = Nakladnoy::findOne($id);
        $updateNak->status = 1;
        $updateNak->save();
        $this->redirect(['supplier-orders']);
    }

    public function actionDone()
    {
        $id = Yii::$app->request->get('id');
        $updateNak = Nakladnoy::findOne($id);
        $updateNak->status = 2;
        $updateNak->save();
        $this->redirect(['supplier-orders']);
    }

    public function actionStatus($id)
    {
        $id = Yii::$app->request->get('id');
        $deleteSupplier = Supplier::findOne($id);
        $deleteSupplier->status = $deleteSupplier->status == 1 ? 0 : 1;
        $deleteSupplier->save();
        $this->redirect(['index']);
    }

    public function actionAbout($id)
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $model = NakladnoyDetails::find()
                ->select('m.name as material, ma.name as mark, nakladnoy_details.quantity')
                ->innerJoin('materials as m',  'nakladnoy_details.material_id = m.id')
                ->innerJoin('marks as ma',  'nakladnoy_details.mark_id = ma.id')
                ->where(['nakladnoy_details.nakladnoy_id' => $id])
                ->asArray()
                ->all();
            return [
                'status' => 'success',
                'content' => $this->renderAjax('view.php',[
                    'model' => $model,
                ]),
            ];
        }
    }

    /**
     * Finds the Supplier model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Supplier the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Supplier::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/supplier/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Yetkazib beruvchilar';
?>
<div class="supplier-index">
    <div class="row">
        <div class="text-left col-md-6">
            <h2 class="m-0"><?= Html::encode($this->title) ?></h2>
        </div>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'format' => 'html',
                'label' => "Ismi",
                'headerOptions' => ['style' => 'color: #3e8ef7 !important;'],
                'value' => function ($data) {
                    $username = $data->name->username;
                    $name = (isset($username) and !empty($username)) ? $username : "Yetkazib beruvchi ismi mavjud emas!";
                    return $name;
                },
            ],
            [
                'format' => 'html',
                'label' => "Holati",
                'headerOptions' => ['style' => 'color: #3e8ef7 !important;'],
                'value' => function ($data) {
                    if ($data->status == 1)
                        $span = " <span class='badge badge-success'>Faol</span>";
                    else
                        $span = "<span class='badge badge-danger'>Faol emas</span>";
                    return $span;
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{status}',
                'buttons' => [
                    'status' => function ($url,$data) {
                        $iconClass = $data->status == 1 ? 'times' : 'check';
                        return Html::a('<i class="fa fa-'.$iconClass.'"></i>', $url);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

<style>
    .supplier-index{
        background-color: white;
        padding: 30px;
        -webkit-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        -moz-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
    }
</style>

views/supplier/nakladnoys.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<div class="nak-orders-index">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="m-0">Nakladnoylar</h2>
        </div>
    </div>

    <table class='table table-bordered table-striped mt-10'>
        <thead>
            <tr>
                <th>#</th>
                <th>Nakladnoy kodi</th>
                <th>Holati</th>
                <th>Batafsil</th>
            </tr>
        </thead>
        <tbody>
        <?php if (isset($model) and !empty($model)): ?>
            <?php $i = 1; foreach ($model as $key => $value): ?>
                <tr>
                    <td><?= $i ?></td>
                    <td><?= $value['code'] ?></td>
                    <?php if ($value['status'] == 0): ?>
                        <td>
                            <a href='<?= \yii\helpers\Url::to(['supplier/start', 'id' => $value['id']]) ?>' class='btn btn-icon btn-sm btn-primary'>
                                <i class='fa fa-hourglass' style='color: white'></i>
                            </a>
                        </td>
                    <?php elseif ($value['status'] == 1): ?>
                        <td>
                            <a href='<?= \yii\helpers\Url::to(['supplier/done', 'id' => $value['id']]) ?>' class='btn btn-icon btn-sm btn-success'>
                                <i class='fa fa-check' style='color: white'></i>
                            </a>
                        </td>
                    <?php elseif ($value['status'] == 2): ?>
                        <td><span class="badge badge-outline badge-primary">Tekshiruvda</span></td>
                    <?php elseif ($value['status'] == 3): ?>
                        <td><span class="badge badge-outline badge-success">Bajarildi</span></td>
                    <?php endif; ?>
                    <td class="w-100">
                        <a href='<?php \yii\helpers\Url::to(['nakladnoy/excel', 'id' => $value['id']]) ?>' class='btn btn-outline btn-sm btn-success'>
                            <i class='fa fa-file-excel-o'></i>
                        </a>
                        <a id="about" data-id="<?= $value['id'] ?>" data-target='#exampleNifty3dSign' data-toggle='modal' class='btn btn-sm btn-outline-dark'>
                            <i class='fa fa-info-circle'></i>
                        </a>
                    </td>
                </tr>
            <?php $i++; endforeach; ?>
        <?php else: ?>
            <tr>
                <td class='text-center' colspan='4'>Ma'lumot yo'q</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>

<style>
    .nak-orders-index {
        background-color: white;
        padding: 30px;
        -webkit-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        -moz-box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
        box-shadow: 5px 5px 7px -4px rgba(0, 0, 0, 0.15);
    }
</style>

<?php
$js = <<<JS
    $(document).on('click', '#about', function(){
        $('.modal-body').html('')
        var id = $(this).attr('data-id')
        $.ajax({
            url: 'about',
            data: {
                id: id
            },
            dataType: 'json',
            type: 'get',
            success: function(response) {
                if (response.status == 'success') {
                    $('.modal-body').html(response.content)
                    $('.modal-header').html("Batafsil").css({fontSize: 23})
                }
            }
        })
    })
JS;
$this->registerJs($js);
?>

views/supplier/view.php
<?php if (isset($model) and !empty($model)): ?>
    <?php foreach ($model as $value): ?>
        <div class="row mt-5">
            <div class="col-md-5">
                <label>Material nomi</label>
                <input type="text" value="<?= $value['material'] ?>" readonly class="form-control" name="">
            </div>
            <div class="col-md-5">
                <label>Marka nomi</label>
                <input type="text" value="<?= $value['mark'] ?>" readonly class="form-control" name="">
            </div>
            <div class="col-md-2">
                <label>Soni</label>
                <input type="text" value="<?= $value['quantity'] ?>" readonly class="form-control" name="">
            </div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <span class="m-0 badge-lg badge badge-outline badge-danger">Ma'lumot mavjud emas</span>
<?php endif ?>